- name: Wait for MySQL container to become ready
  wait_for:
    host: "localhost"
    port: 3308
    delay: 20
    timeout: 120


- name: Copy backup_file1.sql from host to mysql container
  command: docker cp /home/ubuntu/final_assignment2/docker/backup_file1.sql mysql1:/tmp/backup_file1.sql


- name: Import backup_file1.sql into MySQL container

  shell: sudo docker exec -i mysql1 bash -c 'cat /tmp/backup_file1.sql | mysql -u root -pqwerty assignment_database'
  args:
    executable: /bin/bash
