
services:
  mysql:
    image: mysql:latest
    container_name: mysql1
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: assignment_database
      MYSQL_USER: team2_user
      MYSQL_PASSWORD: qwerty
    ports:
      - '3308:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
        mysql-network:
          aliases:
            - mysql
  app:
    build: .
    container_name: python1
    depends_on:
      - mysql
    restart: always
    ports:
      - '8000:8000'
    networks:
      - mysql-network

networks:
  mysql-network:
      driver: bridge
volumes:
  mysql-data:
      driver: local